// Type declarations for @itslil/lil2-hast-util-to-jsx-runtime. Generated by lilscript-work/lil2/release/types.mjs.
/**
 * hast as positional columns: the transformer's own arrays, indexed by node id; `root` is the root's id.
 *
 * A node's kind is `kind[node]`, one of the `H_*` constants of the package that made the columns; an element's tag
 * name is `tagNames[tag[node]]` and text, comment and raw nodes keep their text in `value`. Children run from
 * `firstChild[node]` along `nextSibling`; -1 ends the list and means "none" in every link column. An element's
 * properties run from `propHead[node]` along `propNext`: each has a name (`propNames[propName[p]]`), a kind
 * (`P_*`: string, number, boolean, list, keyword or float) and its value in `propString` (string and list
 * values; a list is space separated) or `propNumber` (numbers, booleans as 0/1, and `P_KEYWORD` ids into
 * `keywordNames`). Positions are offsets into the source; `lineStarts` turns an offset into a line and column.
 */
export type HastColumns = readonly [
  root: number,
  kind: readonly number[],
  parent: readonly number[],
  firstChild: readonly number[],
  nextSibling: readonly number[],
  tag: readonly number[],
  value: readonly string[],
  startOffset: readonly number[],
  endOffset: readonly number[],
  flags: readonly number[],
  meta: readonly string[],
  propHead: readonly number[],
  propName: readonly number[],
  propKind: readonly number[],
  propString: readonly string[],
  propNumber: readonly number[],
  propNext: readonly number[],
  lineStarts: readonly number[],
  tagNames: readonly string[],
]


/** The runtime's `jsx` and `jsxs` (`react/jsx-runtime`, `preact/jsx-runtime`, …). */
export type Jsx<Element> = (type: any, props: any, key?: string) => Element

/** hast-util-to-jsx-runtime's production options, with tag ids for components. */
export interface Options<Element> {
  /** The runtime's `Fragment`. */
  Fragment: unknown
  jsx: Jsx<Element>
  jsxs: Jsx<Element>
  /** `[tag, component, …]` pairs: a tag id (`tagNames.indexOf('h1')`, or a `TAG_*` constant of the package that made
   * the columns), then the component that renders it. */
  components?: readonly unknown[] | null
  /** React keys as upstream makes them (`h1-0`); default true. */
  passKeys?: boolean | null
  /** Give components `node` (an id) and `tree` (the columns, `[kind, parent, …, tagNames]` without the root); default false. */
  passNode?: boolean | null
  /** Turn a table cell's `align` into `style.textAlign`; default true. */
  tableCellAlignToStyle?: boolean | null
}

/**
 * Renders hast columns through a JSX runtime: hast-util-to-jsx-runtime 2's `toJsxRuntime` in production. The columns
 * are the core vocabulary's, from lil2-mdast-util-to-hast, lil2-remark-gfm, lil2-remark-math or lil2-remark-breaks;
 * columns with KaTeX's tags and properties throw (render those with lil2-react-markdown's `/full`).
 */
export declare function toJsxRuntime<Element>(tree: HastColumns, options: Options<Element>): Element
